// <auto-generated />
namespace UOA.ForumData.Analysis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednewquestioncontentattribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednewquestioncontentattribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141043426_Addednewquestioncontentattribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
